-- Inserimenti per Fiat
INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Fiat', '500', 'https://tse1.mm.bing.net/th?id=OIP.yBpvKgvVK-WOftA0JyzeiQHaFk&pid=Api&P=0&h=180', 'Nuovo', '2024-01-01', 0, 'Benzina', 0, 118, 'Automatico', 'Rosso', 20000);

INSERT INTO auto (id, marca, modello, urlimage, condizioni,immatricolazione,chilometraggio, alimentazione, cilindrata, potenza, cambio, colore,prezzo) VALUES(nextval('auto_seq'), 'Fiat', 'Panda','https://tse3.mm.bing.net/th?id=OIP.ol1cQnUswZsfScepEB3zLQAAAA&pid=Api&P=0&h=180','Nuovo','2024-04-06', 20,'Benzina',1000,69,'Manuale','Bianco',15000 );

INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Fiat', 'Tipo', 'https://tse4.mm.bing.net/th?id=OIP.XoUAp-1Rh6Nw-seTMyoiowHaFG&pid=Api&P=0&h=180', 'Usato', '2023-01-01', 15000, 'Diesel', 1600, 120, 'Manuale', 'Grigio', 15000);

-- Inserimenti per Peugeot
INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Peugeot', '3008', 'https://tse4.mm.bing.net/th?id=OIP.BxGAOfMTk75A5CYAfNzzFQHaE8&pid=Api&P=0&h=180', 'Nuovo', '2024-02-01', 0, 'Benzina', 1600, 150, 'Automatico', 'Bianco', 30000);

INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Peugeot', '508', 'https://tse1.mm.bing.net/th?id=OIP.DFlfPcQGxJiiok3l-d_UYQHaE7&pid=Api&P=0&h=180', 'Usato', '2023-02-01', 20000, 'Diesel', 2000, 180, 'Automatico', 'Nero', 25000);

INSERT INTO auto (id, marca, modello, urlimage, condizioni,immatricolazione,chilometraggio, alimentazione, cilindrata, potenza, cambio, colore,prezzo)  VALUES(nextval('auto_seq'), 'Peugeot', '208','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTumRSocgXxpnVDaAve54xL-k1FmSZ4hzXU3A&s','Usato','2022-02-06', 14300,'Diesel',1200,80,'Manuale','Giallo',8000 );


-- Inserimenti per Nissan
INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Nissan', 'Qashqai', 'https://tse3.mm.bing.net/th?id=OIP.QXhMBqkrRw77Z8drP3mLdAHaE8&pid=Api&P=0&h=180', 'Nuovo', '2024-03-01', 0, 'Benzina', 1500, 140, 'Automatico', 'Blu', 28000);

INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Nissan', 'Juke', 'https://tse3.mm.bing.net/th?id=OIP.cxLSEEMa28t2FchWiabNvwHaD4&pid=Api&P=0&h=180', 'Usato', '2023-03-01', 10000, 'Diesel', 0, 114, 'Automatico', 'Rosso', 22000);

-- Inserimenti per BMW
INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'BMW', 'X5', 'https://tse3.mm.bing.net/th?id=OIP.D9XDFWcojp1vL3wpj5ropwHaE6&pid=Api&P=0&h=180', 'Nuovo', '2024-04-01', 0, 'Diesel', 3000, 286, 'Automatico', 'Nero', 50000);

INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'BMW', '320i', 'https://tse4.mm.bing.net/th?id=OIP.6gJjGALwLw9gKT4Ld06Y8gHaEW&pid=Api&P=0&h=180', 'Usato', '2023-04-01', 12000, 'Benzina', 2000, 184, 'Automatico', 'Bianco', 35000);


-- Inserimenti per Citroën
INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Citroen', 'C4', 'https://tse2.mm.bing.net/th?id=OIP.5uKpTZ1aAa6yZMNwP6VFeAHaEK&pid=Api&P=0&h=180', 'Nuovo', '2024-06-01', 0, 'Diesel', 0, 136, 'Automatico', 'Verde', 32000);

INSERT INTO auto (id, marca, modello, urlimage, condizioni, immatricolazione, chilometraggio, alimentazione, cilindrata, potenza, cambio, colore, prezzo) VALUES (nextval('auto_seq'), 'Citroen', 'C3', 'https://tse4.mm.bing.net/th?id=OIP.uuuof8PXb-NfML3VwQgaGwHaE8&pid=Api&P=0&h=180', 'Usato', '2023-06-01', 10000, 'Benzina', 1200, 110, 'Manuale', 'Giallo', 18000);
